### ISSUE TITLE
Not working on 1.5.9 beta branch when entering town

### ISSUE THREAD

**Issue by Efelefem** [3ger/DiplomacyFixes#1]
As described in the title: CTD when entering town (in Sandbox mode).

https://crash.butr.dev/report/D4637E4C.html

**Comment by 3ger** [comment]
Could you please provide a save. And a detailed description on how to reproduce the problem?

**Comment by 3ger** [comment]
This issue was fixed in a new release:
https://github.com/3ger/DiplomacyFixes/releases/tag/1.5.9.1

Please let me know if you encounter any other problems. Don't hesitate to create another issue.
