### ISSUE TITLE
Mod can't be enabled

### ISSUE THREAD

**Issue by raphaelbernhart** [3ger/DiplomacyFixes#10]
I copied the right version of the mod into the Modules folder but when I start the Launcher I can't enable the mod.

Why can't I enable the mod? Screenshot: https://prnt.sc/10rmpmd

Thanks :)

**Comment by 3ger** [comment]
Hi, 

this seems to be related: https://forums.nexusmods.com/index.php?/topic/9073988-diplomacy-fixes-updated/page-23#entry91572513

So do you have the corrent version installed of the dependencies?
In the post linked above it is mentioned how you can change the dependency version and it will still work.

**Comment by raphaelbernhart** [comment]
So you need to install other mods for that mod to work properly?

Maybe you can add dependencies tab on the nexusmods page.

Thanks anyway :)

**Comment by 3ger** [comment]
I'm not maintaining the official mod page at nexusmods. So I can't do it.
