### ISSUE TITLE
Usurping the throne changes the previous king's clans banner

### ISSUE THREAD

**Issue by fridgebro** [3ger/DiplomacyFixes#11]
I usurped the throne of Vlandia and King Derthert's clans banner was changed to a helmet on a purple background and now I want to kick him out just to make the towns red again.
Feature works 100% apart from that though.

**Comment by 3ger** [comment]
What version do you have? 
If possible could you also provide a save game file so I can recreate this faster?

**Comment by fridgebro** [comment]
1.8.1
i'll drop a save here when i can get on my pc

**Comment by fridgebro** [comment]
[king.zip](https://github.com/3ger/DiplomacyFixes/files/6181401/king.zip)
here

**Comment by BalborValis** [comment]
This is a vanilla thing. It’s currently happened in my play though, after Derthart died the owner of Oxs hall took over Vlandia and their banner changed to the lion and Dertharts old clan changed to the full helm.
