### ISSUE TITLE
Crashes on newest version 1.5.9

### ISSUE THREAD

**Issue by Ides3** [3ger/DiplomacyFixes#2]
Unfortunately getting a crash from this mod in Sandbox mode. Didn't occur immediately on first step like crashes usually do, like 15 minutes in. 
https://crash.butr.dev/report/5F48C986.html

**Comment by 3ger** [comment]
Thanks for reporting. Should now be fixed with 1.5.9.2:
https://github.com/3ger/DiplomacyFixes/releases/tag/1.5.9.2

Please let me know if you have any other problems with the new release.
