### ISSUE TITLE
Crashes after so long in 1.5.9 Beta

### ISSUE THREAD

**Issue by Mjdecker1234** [3ger/DiplomacyFixes#3]
https://crash.butr.dev/report/CBC2C5B0.html is the error code

**Comment by 3ger** [comment]
Thanks for reporting. Should now be fixed with 1.5.9.2:
https://github.com/3ger/DiplomacyFixes/releases/tag/1.5.9.2

Please let me know if you have any other problems with the new release.

**Comment by Mjdecker1234** [comment]
> Thanks for reporting. Should now be fixed with 1.5.9.2:
> https://github.com/3ger/DiplomacyFixes/releases/tag/1.5.9.2
> 
> Please let me know if you have any other problems with the new release.

Seems all good now, thank you
