### ISSUE TITLE
1.5.9 Beta Crash

### ISSUE THREAD

**Issue by Lolasik011** [3ger/DiplomacyFixes#6]
https://crash.butr.dev/report/B206F49E.html

**Comment by 3ger** [comment]
I'll look into it, seems some kind of interface problem.

**Comment by 3ger** [comment]
Thank you for reporting

Could you please provide your save(s) and the steps needed to reproduce? Thanks in advance!

**Comment by Lolasik011** [comment]
> Thank you for reporting
> 
> Could you please provide your save(s) and the steps needed to reproduce? Thanks in advance!

Sorry i dont have save file :(

**Comment by 3ger** [comment]
Did you have any problems regarding this issue? Could you reproduce it again?
