### ISSUE TITLE
About Messengers

### ISSUE THREAD

**Issue by myilmaz38** [3ger/DiplomacyFixes#7]
I can only send messengers to other rulers with kingdom page. Otherwise i can't talk with other nobles and wanderers. I don't see any button or sign at library page about sending messenger. Seems there is a collision with Intrigues mod. When i disabled that, it works well. Can you handle that issue?

**Comment by 3ger** [comment]
Hi, sorry currently not going to fix problems with other mods.
I might look into it in the future, but I can't promise you that.

Why not do it yourself? I would gladly assist with any questions you have in the process. 😄

**Comment by myilmaz38** [comment]
It is not a huge problem man, i can gladly disable other mods which have collision with this. Thx anyway. :)
