### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by streetdapper** [3ger/DiplomacyFixes#8]
https://imgur.com/a/bwHAqHT
 Possible bug due to diplomacy. Not sure though but let me know.

**Comment by streetdapper** [comment]
Okay, i have replicated this error message 3 times now and in each of these scenarios is that i am in a faction whether I'm a mercenary or a vassal when i leave the faction i am in through the diplomacy menu or by talking to the faction leader i get this error.

**Comment by 3ger** [comment]
Thank you for reporting the issue.
Could you provide a save file? Thanks in advance.
