### ISSUE TITLE
constant war

### ISSUE THREAD

**Issue by Rul1n** [3ger/DiplomacyFixes#9]
I started a new game (v1.5.9b) with this mod and after joining battania (maybe even before), the faction is in constant war against his neighbors. Not sure if this is vanilla behaviour, or if it has something to do with this mod. Just wanted to mention it here.
Here is my current modlist: https://i.imgur.com/FifMAET.png

**Comment by 3ger** [comment]
If you provide a save game file I could take a look.

**Comment by Rul1n** [comment]
[Schlacht.zip](https://github.com/3ger/DiplomacyFixes/files/6180877/Schlacht.zip)

**Comment by Rul1n** [comment]
![grafik](https://user-images.githubusercontent.com/72325265/111983995-1b120900-8b0b-11eb-9bac-5c0b86cadfd7.png)
Just reached a moment in peace with everyone. What do these numbers next to the faction mean?

**Comment by Rul1n** [comment]
After reading some posts in the Forums, I think this might be a vanilla game problem.
https://forums.taleworlds.com/index.php?threads/constant-warfare-did-taleworld-adress-that.441099/
https://forums.taleworlds.com/index.php?threads/endless-wars-in-1-5-7-how-to-make-a-faction-make-peace-with-everyone.439380/page-2

**Comment by BalborValis** [comment]
Is the non-aggression after peace different from a forming a proper non-aggression pact?
